name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


jobs:

  # Job build
  build:
    name: Build and Test the service
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.2.0

      - name: Set up JDK
        id: setup_jdk
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build
        id: build
        run: mvn -B package --file pom.xml

      - name: Run Tests
        id: test
        run: |
          mvn clean test

      - name: Check filename
        id: check_filename
        run: |
          cd target
          echo "FILENAME=$(ls *.jar)" >> $GITHUB_ENV
    outputs:
      filename: ${{ env.FILENAME }}

  # Job print-status
  print-status:
    name: Printing jar file name
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git checkout
        uses: actions/checkout@v3.2.0

      - name: Print file name
        run: echo '${{ needs.build.outputs.filename }}'
